CREATE DATABASE IF NOT EXISTS backend_tasks
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE backend_tasks;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;


